dist: trusty
language: node_js
node_js:
- 6

addons:
  apt:
    packages:
      - pulseaudio

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=esr

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - pulseaudio --start
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test && npm run test-travis

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

